services:
  postgres:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=cinema-webapp
      - POSTGRES_PASSWORD=IU0IGyIY97ihi3gIYtgIU56UYg
    ports:
        - '5432:5432'
    volumes:
        - ./postgres-data:/var/lib/postgresql/data